--APAGANDO BANCO DE DADOS CURSO
USE MASTER
GO
DROP DATABASE CURSO

--DDL CRIANDO UM DATABASE
CREATE DATABASE CURSO

--CRIANDO UM DATABASE COM ARQUIVOS PRIMÁRIO, SECUNDARIO E LOG
USE MASTER
GO
CREATE DATABASE AULA_DDL
 ON  PRIMARY 
( 
  NAME = N'AULA_DDL_PRIM', FILENAME = N'K:\SQL001\AULA_DDL_PRIM.mdf' , 
  SIZE = 4MB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  ),
  FILEGROUP FG_AULA_1
  (
  NAME = N'AULA_DDL1', FILENAME = N'k:\SQL001\AULA_DDL1.ndf' , 
  SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  ),
   (
  NAME = N'AULA_DDL2', FILENAME = N'k:\SQL001\AULA_DDL2.ndf' , 
  SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  )
 LOG ON 
( NAME = N'AULA_DDL_LOG', FILENAME = N'L:\SQL001\AULA_DDL_log.ldf' , 
  SIZE = 10MB , MAXSIZE = 2048MB , FILEGROWTH = 10%);
GO
--ALTERANDO 

ALTER DATABASE AULA_DDL 
  MODIFY FILEGROUP FG_AULA_1 DEFAULT;
GO








