--CRIAR LOGONS SERVIDOR/INSTANCIA
--NIVEL ADM
-- USER DBA_AULA SENHA Sql2017@!
-- USER DBA_CURSO SENHA Sql2017@!
-- USER DBA_MINI_CRM SENHA Sql2017@!

--NIVEL COMUM/NORMAL
--USUARIOS ADM
-- USER USR_AULA SENHA Sql2017@!
-- USER USR_CURSO SENHA Sql2017@!
-- USER USR_MINI_CRM SENHA Sql2017@!

--ACESSO BANCO DE DADOS
--CRIAR USUARIOS DE BANCO (ASSOCIAR LOGIN X USERS)
-- USER DBA_AULA X LOGIN DBA_AULA
-- USER DBA_CURSO X LOGIN DBA_AULA
-- USER DBA_MINI_CRM X LOGIN DBA_MINI_CRM

-- USER USR_AULA X LOGIN USR_AULA
-- USER USR_CURSO X LOGIN USR_CURSO
-- USER USR_MINI_CRM X LOGIN USR_MINI_CRM

--VERIFICANDO PROPRIETÁRIO  DB
	SP_HELPDB AULA_DDL
	SP_HELPDB CURSO
	SP_HELPDB MINICRM
--ALTERANDO PROPRIETARIOS
USE MASTER
ALTER AUTHORIZATION ON DATABASE::AULA_DDL TO DBA_AULA;
ALTER AUTHORIZATION ON DATABASE::CURSO TO DBA_CURSO;
ALTER AUTHORIZATION ON DATABASE::MINICRM TO DBA_MINI_CRM;

--VERIFICA
--VERIFICANDO PROPRIETÁRIO  DB
	SP_HELPDB AULA_DDL
	SP_HELPDB CURSO
	SP_HELPDB MINICRM


 