--CRIANDO OBJETOS PARA TESTE
--LOGAR COM USUARIO DBA_MINI_CRM
USE MINICRM
GO


-- Verificando as permissões do usuário "USR_MINI_CRM"
EXEC MINICRM.dbo.sp_helprotect 
    @username = 'USR_MINI_CRM'    

    
--CRIAR UMA PROC
USE MINICRM
GO

CREATE PROCEDURE PROC_AGENDA_MES
  AS
   BEGIN 
	SELECT CONVERT(VARCHAR(7) ,DATA_VISITA,111)AS ANO_MES,COUNT(*) QTD
	FROM AGENDA
	GROUP BY CONVERT(VARCHAR(7) ,DATA_VISITA,111)
   END

--CRIANDO OUTRA PROCEDURE
CREATE PROCEDURE PROC_AGENDA_ANO
  AS
   BEGIN 
	SELECT CONVERT(VARCHAR(4) ,DATA_VISITA,111)AS ANO_MES,COUNT(*) QTD
	FROM AGENDA
	GROUP BY CONVERT(VARCHAR(4) ,DATA_VISITA,111)
   END
--CRIANDO UMA FUNÇÃO
CREATE FUNCTION FN_AGENDA (@MAT_VEND INT)
 RETURNS TABLE
  AS
  RETURN (SELECT MATRICULA,COUNT(*) AS NUM_AGENDAS FROM AGENDA
            WHERE MATRICULA=@MAT_VEND
			GROUP BY MATRICULA)

--CRIANDO FUNÇÃO
CREATE FUNCTION FN_AGENDA_CLI (@ID_CLI INT)
 RETURNS TABLE
  AS
  RETURN (SELECT ID_CLIENTE,COUNT(*) AS NUM_AGENDAS FROM AGENDA
            WHERE ID_CLIENTE=@ID_CLI
			GROUP BY ID_CLIENTE)
--INVOCANDO
SELECT * FROM FN_AGENDA_CLI('1') 
--Parte 1 CONCEDE-GRANT
-- Cria um login e dá permissões no banco

/*
Permissões de função escalar: EXECUTE, REFERENCES.
Permissões de função com valor de tabela: DELETE, INSERT, REFERENCES, SELECT, UPDATE.
Permissões de procedimento armazenado: EXECUTE.
Permissões de tabela: DELETE, INSERT, REFERENCES, SELECT, UPDATE.
Permissões de exibição(views): DELETE, INSERT, REFERENCES, SELECT, UPDATE.
*/
--Referencia
--https://docs.microsoft.com/pt-br/sql/t-sql/statements/grant-object-permissions-transact-sql?view=sql-server-2017

--Concedendo Acesso DE ATUALIZACAO PARA USR_MINI_CRM.
GRANT UPDATE ON AGENDA TO USR_MINI_CRM; 

--Concedendo Acesso DE INSERT PARA USR_MINI_CRM.
GRANT INSERT ON AGENDA TO USR_MINI_CRM; 
--SETUSER
GRANT INSERT ON USUARIOS TO USR_MINI_CRM; 

--Concedendo Acesso DE Leitura PARA USR_MINI_CRM.
--GRANT OPTION USUARIO PODE CONCEDER O QUE ACESSO QUE TEM PARA OUTRO USER
GRANT SELECT ON AGENDA TO USR_MINI_CRM WITH GRANT OPTION;

--Concedendo Acesso DE Leitura PARA USR_MINI_CRM.
--GRANT OPTION USUARIO PODE CONCEDER O QUE ACESSO QUE TEM PARA OUTRO USER
GRANT SELECT ON USUARIOS(LOGIN,MATRICULA) TO USR_MINI_CRM 

--Concedendo Acesso DE DELETE PARA USR_MINI_CRM.
GRANT DELETE ON FOLLOW_UP_AGENDA TO USR_MINI_CRM;
--extra

--Concedendo Acesso DE SELECT PARA USR_MINI_CRM.
GRANT SELECT  ON FOLLOW_UP_AGENDA TO USR_MINI_CRM;

--Concedendo Acesso PARA CRIAR VIEW PARA USR_MINI_CRM.
GRANT CREATE VIEW TO USR_MINI_CRM;

--Concedendo Acesso PARA CRIAR TABELA PARA USR_MINI_CRM.
GRANT CREATE TABLE TO USR_MINI_CRM;

--GRANTS GERAL
 GRANT SELECT TO USR_MINI_CRM
 GRANT UPDATE TO USR_MINI_CRM
 GRANT INSERT TO USR_MINI_CRM
 GRANT DELETE TO USR_MINI_CRM
 GRANT EXECUTE TO USR_MINI_CRM

 GRANT SELECT,UPDATE,INSERT,DELETE,EXECUTE TO USR_MINI_CRM

--Concedendo Acesso PARA CRIAR PROCEDURE PARA USR_MINI_CRM.
GRANT CREATE PROCEDURE TO USR_MINI_CRM;

--Concedendo Acesso PARA CRIAR FUNCTION PARA USR_MINI_CRM.
GRANT CREATE FUNCTION TO USR_MINI_CRM;


--Concedendo Acesso PARA EXCUTAR PROC TESTE_PROC PARA USR_MINI_CRM.
GRANT EXECUTE ON PROC_AGENDA_MES TO USR_MINI_CRM  

--Concedendo Acesso PARA FUNCTION FN_AGENDA_CLI PARA USR_MINI_CRM.
GRANT SELECT ON FN_AGENDA TO USR_MINI_CRM;  

-- Verificando as permissões do usuário "USR_MINI_CRM"
EXEC MINICRM.dbo.sp_helprotect  @username = 'USR_MINI_CRM'    

--VERIFICANDO PERMISSOES NO OBJETO
EXEC MINICRM.dbo.sp_helprotect  'USUARIOS'    
EXEC MINICRM.dbo.sp_helprotect  'AGENDA'    


     

--OPÇÕES DE GRANT
USE MINICRM;
GO
GRANT
       ALTER,
       ALTER ANY ASSEMBLY,
       AUTHENTICATE,
       CONNECT,
       CREATE AGGREGATE,
       CREATE ASSEMBLY,
       CREATE DEFAULT,
       CREATE FUNCTION,
       CREATE PROCEDURE,
       CREATE SYNONYM,
       CREATE TABLE,
       CREATE VIEW,
       DELETE,
       EXECUTE,
       INSERT,
       REFERENCES,
       SELECT,
       SHOWPLAN,
       UPDATE,
       VIEW DATABASE STATE,
       VIEW DEFINITION
TO USR_MINI_CRM;
GO

