--CRIANDO OBJETOS PARA TESTE
--LOGAR COM USUARIO DBA_MINI_CRM
USE MINICRM
GO

-- Verificando as permissões do usuário "USR_MINI_CRM"
EXEC MINICRM.dbo.sp_helprotect 
    @username = 'USR_MINI_CRM'    

    
--Parte 1 REVOGA-REVOKE
-- REVOGA PERMISSÕES DE  LOGIN

--Referencia
--https://docs.microsoft.com/pt-br/sql/t-sql/statements/revoke-object-permissions-transact-sql?view=sql-server-2017

--Revogando Acesso DE ATUALIZACAO PARA USR_MINI_CRM.
REVOKE UPDATE ON AGENDA FROM  USR_MINI_CRM; 

--Revogando Acesso DE INSERT PARA USR_MINI_CRM.
REVOKE INSERT ON AGENDA FROM USR_MINI_CRM; 
--SETUSER
REVOKE INSERT ON USUARIOS FROM USR_MINI_CRM; 

--Revogando a opção WITH GRANT
REVOKE GRANT OPTION FOR SELECT ON AGENDA FROM USR_MINI_CRM CASCADE

--Revogando Acesso DE Leitura PARA USR_MINI_CRM.
--REVOKE OPTION USUARIO PODE CONCEDER O QUE ACESSO QUE TEM PARA OUTRO USER
/*
CASCADE
Indica que a permissão que está sendo revogada também é revogada de outros 
principais aos quais ela foi concedida ou negada por esse principal.
*/

REVOKE SELECT ON AGENDA FROM USR_MINI_CRM;

--Revogando Acesso DE Leitura PARA USR_MINI_CRM.
REVOKE SELECT ON USUARIOS(LOGIN,MATRICULA) FROM USR_MINI_CRM 

--Revogando Acesso DE DELETE PARA USR_MINI_CRM.
REVOKE DELETE ON FOLLOW_UP_AGENDA FROM USR_MINI_CRM;
--extra

--Revogando Acesso DE SELECT PARA USR_MINI_CRM.
REVOKE SELECT  ON FOLLOW_UP_AGENDA FROM USR_MINI_CRM;

--Revogando Acesso PARA CRIAR VIEW PARA USR_MINI_CRM.
REVOKE CREATE VIEW FROM USR_MINI_CRM;

--Revogando Acesso PARA CRIAR TABELA PARA USR_MINI_CRM.
REVOKE CREATE TABLE FROM USR_MINI_CRM;

--REVOKES GERAL
 REVOKE SELECT FROM USR_MINI_CRM
 REVOKE UPDATE FROM USR_MINI_CRM
 REVOKE INSERT FROM USR_MINI_CRM
 REVOKE DELETE FROM USR_MINI_CRM
 REVOKE EXECUTE FROM USR_MINI_CRM

 REVOKE SELECT,UPDATE,INSERT,DELETE,EXECUTE FROM USR_MINI_CRM

--Revogando Acesso PARA CRIAR PROCEDURE PARA USR_MINI_CRM.
REVOKE CREATE PROCEDURE FROM USR_MINI_CRM;

--Revogando Acesso PARA CRIAR FUNCTION PARA USR_MINI_CRM.
REVOKE CREATE FUNCTION FROM USR_MINI_CRM;


--Revogando Acesso PARA EXCUTAR PROC TESTE_PROC PARA USR_MINI_CRM.
REVOKE EXECUTE ON PROC_AGENDA_MES FROM USR_MINI_CRM  

--Revogando Acesso PARA FUNCTION FN_AGENDA_CLI PARA USR_MINI_CRM.
REVOKE SELECT ON FN_AGENDA FROM USR_MINI_CRM;  

-- Verificando as permissões do usuário "USR_MINI_CRM"
EXEC MINICRM.dbo.sp_helprotect  @username = 'USR_MINI_CRM'    

--VERIFICANDO PERMISSOES NO OBJETO
EXEC MINICRM.dbo.sp_helprotect  'USUARIOS'    
EXEC MINICRM.dbo.sp_helprotect  'AGENDA'    


     

--OPÇÕES DE REVOKE
USE MINICRM;
GO
REVOKE
       ALTER,
       ALTER ANY ASSEMBLY,
       AUTHENTICATE,
       CONNECT,
       CREATE AGGREGATE,
       CREATE ASSEMBLY,
       CREATE DEFAULT,
       CREATE FUNCTION,
       CREATE PROCEDURE,
       CREATE SYNONYM,
       CREATE TABLE,
       CREATE VIEW,
       DELETE,
       EXECUTE,
       INSERT,
       REFERENCES,
       SELECT,
       SHOWPLAN,
       UPDATE,
       VIEW DATABASE STATE,
       VIEW DEFINITION
FROM USR_MINI_CRM;
GO

