--CRIANDO OBJETOS PARA TESTE
--LOGAR COM USUARIO DBA_MINI_CRM
USE MINICRM
GO

-- Verificando as permissões do usuário "USR_MINI_CRM"
EXEC MINICRM.dbo.sp_helprotect 
    @username = 'USR_MINI_CRM'    
--CONCEDENDO PERMISSÕES
--DENY GERAL
 GRANT SELECT TO  USR_MINI_CRM
 GRANT UPDATE TO  USR_MINI_CRM
 GRANT INSERT TO  USR_MINI_CRM
 GRANT DELETE TO  USR_MINI_CRM
 GRANT EXECUTE TO  USR_MINI_CRM

-- Verificando as permissões do usuário "USR_MINI_CRM"
EXEC MINICRM.dbo.sp_helprotect 
    @username = 'USR_MINI_CRM'    
--Parte 1 REVOGA-DENY
-- REVOGA PERMISSÕES DE  LOGIN

--Referencia
--https://docs.microsoft.com/pt-br/sql/t-sql/statements/DENY-object-permissions-transact-sql?view=sql-server-2017

--Negando Acesso DE ATUALIZACAO PARA USR_MINI_CRM.
DENY UPDATE ON AGENDA TO  USR_MINI_CRM; 

--Negando Acesso DE INSERT PARA USR_MINI_CRM.
DENY INSERT ON AGENDA TO USR_MINI_CRM; 

--Negando Acesso DE INSERT PARA USR_MINI_CRM.
DENY INSERT ON USUARIOS TO USR_MINI_CRM; 

--Negando Acesso DE LEITURA PARA USR_MINI_CRM.
DENY SELECT ON AGENDA TO USR_MINI_CRM;


--Negando Acesso DE DELETE PARA USR_MINI_CRM.
DENY DELETE ON FOLLOW_UP_AGENDA TO USR_MINI_CRM;
--extra

--Negando Acesso DE SELECT PARA USR_MINI_CRM.
DENY SELECT  ON FOLLOW_UP_AGENDA TO USR_MINI_CRM;

--Negando Acesso PARA CRIAR VIEW PARA USR_MINI_CRM.
DENY CREATE VIEW TO USR_MINI_CRM;

--Negando Acesso PARA CRIAR TABELA PARA USR_MINI_CRM.
DENY CREATE TABLE TO USR_MINI_CRM;
--Negando Acesso PARA CRIAR PROCEDURE PARA USR_MINI_CRM.
DENY CREATE PROCEDURE TO USR_MINI_CRM;

--Negando Acesso PARA CRIAR FUNCTION PARA USR_MINI_CRM.
DENY CREATE FUNCTION TO USR_MINI_CRM;


--Negando Acesso PARA EXCUTAR PROC TESTE_PROC PARA USR_MINI_CRM.
DENY EXECUTE ON PROC_AGENDA_MES TO USR_MINI_CRM  

--Negando Acesso PARA FUNCTION FN_AGENDA_CLI PARA USR_MINI_CRM.
DENY SELECT ON FN_AGENDA TO USR_MINI_CRM;  

-- Verificando as permissões do usuário "USR_MINI_CRM"
EXEC MINICRM.dbo.sp_helprotect  @username = 'USR_MINI_CRM'    

--VERIFICANDO PERMISSOES NO OBJETO
EXEC MINICRM.dbo.sp_helprotect  'USUARIOS'    
EXEC MINICRM.dbo.sp_helprotect  'AGENDA'    



--DENYS GENERICOS
 DENY SELECT TO USR_MINI_CRM
 DENY UPDATE TO USR_MINI_CRM
 DENY INSERT TO USR_MINI_CRM
 DENY DELETE TO USR_MINI_CRM
 DENY EXECUTE TO USR_MINI_CRM

 DENY SELECT,UPDATE,INSERT,DELETE,EXECUTE TO USR_MINI_CRM
  


     

--OPÇÕES DE DENY
USE MINICRM;
GO
DENY
       ALTER,
       ALTER ANY ASSEMBLY,
       AUTHENTICATE,
       CONNECT,
       CREATE AGGREGATE,
       CREATE ASSEMBLY,
       CREATE DEFAULT,
       CREATE FUNCTION,
       CREATE PROCEDURE,
       CREATE SYNONYM,
       CREATE TABLE,
       CREATE VIEW,
       DELETE,
       EXECUTE,
       INSERT,
       REFERENCES,
       SELECT,
       SHOWPLAN,
       UPDATE,
       VIEW DATABASE STATE,
       VIEW DEFINITION
TO USR_MINI_CRM;
GO

