-- CRIA DATABASE AULA_SCHEMA
--DROP DATABASE AULA_SCHEMA
-- DROP LOGIN USR_VEND
-- DROP LOGIN USR_FIN
  CREATE DATABASE AULA_SCHEMA


-- Criando Schema para a área de VENDAS

use AULA_SCHEMA
GO 
CREATE SCHEMA VENDA
GO

-- Criando Schema para a área de FINANCEIRA 
CREATE SCHEMA FINANCEIRO
GO

-- Criando Schema para a área de HISTORICO 
CREATE SCHEMA HISTORICO
GO

-- Criando tabela PEDIDOS no Schema VENDA
CREATE TABLE VENDA.PEDIDOS(
	NUM_PEDIDO int NOT NULL PRIMARY KEY,
	ID_CLIENTE varchar(50) NULL,
	DATA_ENTREGA DATE NOT NULL,
	VALOR decimal(18, 0) NULL
) 

--CRIANDO UMA TABELA DE HISTORICO
CREATE TABLE VENDA.HIST_PEDIDOS(
	NUM_PEDIDO int NOT NULL PRIMARY KEY,
	ID_CLIENTE varchar(50) NULL,
	DATA_ENTREGA DATE NOT NULL,
	VALOR decimal(18, 0) NULL
) 
-- Criando tabela CONTAS_PAGAR no Schema VENDAS
CREATE TABLE VENDA.CONTAS_PAGAR(
	NUM_PEDIDO int NOT NULL PRIMARY KEY,
	ID_CLIENTE varchar(50) NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	DATA_PAGTO DATE NOT NULL,
	VALOR decimal(18, 0) NULL
) 


/* Alterando o Schema da tabela CONTAS_PAGAR. */

ALTER SCHEMA FINANCEIRO TRANSFER VENDA.CONTAS_PAGAR
GO
/* Alterando o Schema da tabela CONTAS_PAGAR. */


ALTER SCHEMA HISTORICO TRANSFER VENDA.HIST_PEDIDOS
GO

--TESTE DE SELECT NO SCHEMA 
select * from VENDA.PEDIDOS
select * from HISTORICO.HIST_PEDIDOS
select * from FINANCEIRO.CONTAS_PAGAR

--DROP SCHEMAS
DROP SCHEMA VENDA
DROP SCHEMA FINANCEIRO
DROP SCHEMA HISTORICO


--VERIFICANDO TODOS SCHEMAS
select * from sys.schemas 