--CRIAR 2 USUARIOS
--  [USR_VEND]  -- PARA AREA COMERCIAL
--  [USR_FIN]   -- PARA AREA FINANCEIRA
--USER COMERCIAL
USE [master]
GO
CREATE LOGIN [USR_VEND] WITH PASSWORD=N'Sql2017@!', 
	DEFAULT_DATABASE=[AULA_SCHEMA], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [AULA_SCHEMA]
GO
CREATE USER [USR_VEND] FOR LOGIN [USR_VEND]
GO
USE [AULA_SCHEMA]
GO
ALTER ROLE [db_datareader] ADD MEMBER [USR_VEND]
GO
USE [AULA_SCHEMA]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [USR_VEND]
GO

--USER FINANCEIRO
USE [master]
GO
CREATE LOGIN [USR_FIN] WITH PASSWORD=N'Sql2017@!', 
	DEFAULT_DATABASE=[AULA_SCHEMA], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [AULA_SCHEMA]
GO
CREATE USER [USR_FIN] FOR LOGIN [USR_FIN]
GO
USE [AULA_SCHEMA]
GO
ALTER ROLE [db_datareader] ADD MEMBER [USR_FIN]
GO
USE [AULA_SCHEMA]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [USR_FIN]
GO

--TESTANDO SELECT SIMULANDO USUARIO USR_VEND

EXECUTE AS USER='USR_VEND'
--teste
SELECT SYSTEM_USER
SELECT * FROM VENDA.PEDIDOS
SELECT * FROM HISTORICO.HIST_PEDIDOS
SELECT * FROM FINANCEIRO.CONTAS_PAGAR
REVERT
SELECT SYSTEM_USER

--TESTANDO SELECT SIMULANDO USUARIO USR_FIN

EXECUTE AS USER='USR_FIN'
SELECT SYSTEM_USER
SELECT * FROM VENDA.PEDIDOS
SELECT * FROM HISTORICO.HIST_PEDIDOS
SELECT * FROM FINANCEIRO.CONTAS_PAGAR
REVERT
SELECT SYSTEM_USER

--Permissões
--Comercial
GRANT SELECT ON SCHEMA::VENDA TO USR_VEND  
GRANT SELECT ON SCHEMA::HISTORICO TO USR_VEND 
DENY SELECT ON SCHEMA::FINANCEIRO TO USR_VEND 
--Financeiro
DENY SELECT ON SCHEMA::VENDA TO USR_FIN  
DENY SELECT ON SCHEMA::HISTORICO TO USR_FIN 
GRANT SELECT ON SCHEMA::FINANCEIRO TO USR_FIN 

--Testar acesso
--comercial
EXECUTE AS USER='USR_VEND'
SELECT SYSTEM_USER
SELECT * FROM VENDA.PEDIDOS
SELECT * FROM HISTORICO.HIST_PEDIDOS
SELECT * FROM FINANCEIRO.CONTAS_PAGAR
REVERT
SELECT SYSTEM_USER

--TESTANDO SELECT SIMULANDO USUARIO USR_FIN

EXECUTE AS USER='USR_FIN'
SELECT SYSTEM_USER
SELECT * FROM VENDA.PEDIDOS
SELECT * FROM HISTORICO.HIST_PEDIDOS
SELECT * FROM FINANCEIRO.CONTAS_PAGAR
REVERT
SELECT SYSTEM_USER
