--BACKUP 

USE MASTER
GO
--BANCO DE MODO DE RECUPERAÇÃO COMPLETO
ALTER DATABASE MINICRM SET RECOVERY FULL
--BACKUP NORMAL
BACKUP DATABASE MINICRM
 TO DISK = 'M:\SQL001\MINICRM_1_FULL.BAK'
   WITH STATS

--BACKUP COMPRIMIDO
BACKUP DATABASE MINICRM
 TO DISK = 'M:\SQL001\MINICRM_2_FULL.BAK'
   WITH COMPRESSION,STATS

--DROP DATABASE
USE MASTER
GO
DROP DATABASE MINICRM

--RESTORE 
RESTORE DATABASE MINICRM
FROM  DISK = 'M:\SQL001\MINICRM_1_FULL.BAK'
   WITH STATS,RECOVERY

--OPCAO
--RESTORE 
RESTORE DATABASE MINICRM
FROM  DISK = 'M:\SQL001\MINICRM_2_FULL.BAK'
   WITH STATS,NORECOVERY
--COLOCAR ONLINE
RESTORE DATABASE MINICRM WITH RECOVERY
