--MULTIPLOS ARQUIVOS DE BACKUP
USE MASTER
GO
--APANGO EXEMPLO ANTERIOR
DROP DATABASE AULA_BK
--CRIANDO O BANCO
CREATE DATABASE AULA_BK
GO
USE AULA_BK

--CRIANDO TABELA
CREATE TABLE REGISTROS (
	ID_REGISTRO INT IDENTITY(1,1)PRIMARY KEY,
	CARGA VARCHAR (50),	
)
GO

--Passo 5
--Populando Tabela COM 100000 REGISTRO
--DEMOROU 09:34 
--NAO FAZER--
--INSERT INTO REGISTROS VALUES ('1 CARGA')
--GO 100000

--CRIANDO PROC PARA OTIMIZAR A CARGA
CREATE PROCEDURE PROC_CARGA (@QTD_INSERT INT)
 AS
 --DECLARE VARIAVEIS
 DECLARE
  @HORA_INI AS DATETIME,
  @HORA_FIM AS DATETIME,
  @QTD_COMMIT AS INT,
  @CONTADOR AS INT,
  @DURACAO AS INT
   BEGIN 
   --ABRE TRANSAÇÃO
   BEGIN TRANSACTION
   --INICIA VALORES  
	   SET @CONTADOR=0
	   SET @QTD_COMMIT=0;
	   SET @HORA_INI=GETDATE()
	   --IMPRIMI HORA INICIO
	   SELECT 'INICIO '+CAST(@HORA_INI AS VARCHAR(50))
    --INICIA WHILE
   WHILE @CONTADOR<@QTD_INSERT
    BEGIN 
	 INSERT INTO REGISTROS VALUES ('1 CARGA');
	 --CONTADORES
	 SET @CONTADOR=@CONTADOR+1;
	 SET @QTD_COMMIT=@QTD_COMMIT+1;
	 --SE QTD REGISTRO IGUAL 1000 REALIZAR COMITT E ABRE NOVA TRANSACAO
		  IF @QTD_COMMIT=1000 BEGIN
       		   SET @QTD_COMMIT=0
			   COMMIT;
			   BEGIN TRANSACTION; 
		  END
      --FIM IF
	END
	--FIM WHILE
	COMMIT
	SET @HORA_FIM=GETDATE()
		--IMPRIMI HORA FIM
		SELECT 'FIM '+CAST(@HORA_FIM AS VARCHAR(50))
		SET @DURACAO=DATEDIFF(SECOND,@HORA_INI,@HORA_FIM)
		--IMPRIMI DURACAO
		SELECT 'DURACAO '+CAST(@DURACAO AS VARCHAR(50))+' Segs'
	END
	--FIM PROCEDURE

--EXEC PROC_CARGA    
	EXEC PROC_CARGA 1000000

--EVIDENCIA A CARGA
SELECT COUNT(*) FROM REGISTROS
--SE EXISTE TRANSAÇÃO ABERTA
SELECT @@TRANCOUNT
--EXPLICANDO
--ABRE TRANSAÇAO
BEGIN TRAN
--VERIFICA TRANSACAO
SELECT @@TRANCOUNT
--FECHA TRANSACAO PELO COMMIT OU ROLLBACK
COMMIT
--VERIFICA TRANSACAO
SELECT @@TRANCOUNT

--BACKUP MULTIPLOS ARQUIVOS 
BACKUP DATABASE AULA_BK
TO DISK = 'M:\SQL001\AULA_BK1.BAK',
   DISK = 'M:\SQL001\AULA_BK2.BAK',
   DISK = 'M:\SQL001\AULA_BK3.BAK',
   DISK = 'M:\SQL001\AULA_BK4.BAK'
   WITH STATS

--BACKUP LOG
BACKUP LOG AULA_BK TO DISK = 'M:\SQL001\AULA_BK1_M_LOG1.TRN'
   
--RESTORE MULTIPLOS ARQUIVOS
USE MASTER
GO
RESTORE DATABASE AULA_BK
FROM  DISK = 'M:\SQL001\AULA_BK1.BAK',
	  DISK = 'M:\SQL001\AULA_BK2.BAK',
      DISK = 'M:\SQL001\AULA_BK3.BAK',
      DISK = 'M:\SQL001\AULA_BK4.BAK'
      WITH STATS,REPLACE,NORECOVERY

--COLOCANDO NO AR
USE MASTER
RESTORE DATABASE AULA_BK WITH RECOVERY

--EVIDENCIA RESTORE
USE AULA_BK
SELECT COUNT(*) FROM REGISTROS



