--CRIANDO DATABASE
CREATE DATABASE AULA_ANEXO1
 ON  PRIMARY 
( 
  NAME = N'AULA_AT1', FILENAME = N'k:\SQL001\AULA_AT1.mdf' , 
  SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  ),
  FILEGROUP ANEXO
  (
  NAME = N'AULA_AT2', FILENAME = N'k:\SQL001\AULA_AT2.ndf' , 
  SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  ),
   (
  NAME = N'AULA_AT3', FILENAME = N'k:\SQL001\AULA_AT3.ndf' , 
  SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  )
 LOG ON 
( NAME = N'AULA_AT_log', FILENAME = N'L:\SQL001\AULA_AT_log.ldf' , 
  SIZE = 1072KB , MAXSIZE = 2048MB , FILEGROWTH = 10%)

--DESANEXANDO
USE master;  
GO  
EXEC sp_detach_db @dbname = N'AULA_ANEXO1';  
GO 

--ANEXANDO
CREATE DATABASE AULA_ANEXO1   
    ON (FILENAME = 'k:\SQL001\AULA_AT1.mdf'),
	   (FILENAME = 'k:\SQL001\AULA_AT2.ndf'),
	   (FILENAME = 'k:\SQL001\AULA_AT3.ndf'),
	   (FILENAME = 'L:\SQL001\AULA_AT_log.ldf') 
    FOR ATTACH;  
GO  


--CRIANDO DATABASE
CREATE DATABASE AULA_ANEXO2
 ON  PRIMARY 
( 
  NAME = N'AULA_AT2', FILENAME = N'k:\SQL001\AULA_AT2.mdf' , 
  SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB 
  )
 LOG ON 
( NAME = N'AULA_AT2_log', FILENAME = N'L:\SQL001\AULA_AT2_log.ldf' , 
  SIZE = 1072KB , MAXSIZE = 2048MB , FILEGROWTH = 10%)

--DESANEXANDO
USE master;  
GO  
EXEC sp_detach_db @dbname = N'AULA_ANEXO2';  
GO 

--ANEXANDO
CREATE DATABASE AULA_ANEXO2   
    ON (FILENAME = 'k:\SQL001\AULA_AT2.mdf'),
	   (FILENAME = 'L:\SQL001\AULA_AT2_log.ldf') 
    FOR ATTACH;  
GO  
