--SESSÃO 1
USE CURSO
SELECT @@SPID --56
BEGIN TRAN

SELECT * FROM SALDO_CORRENTE WITH(UPDLOCK)
WHERE ID_AGENCIA='9000' AND ID_CONTA='100001'

--UPDATE SALDO_CORRENTE SET SALDO=700 WHERE ID_AGENCIA='9000' AND ID_CONTA='100001'

--REALIZAR COMMIT OU ROLLBACK
COMMIT
ROLLBACK