 --SESSÃO 1
--2. Abrir outra sessão e execute os seguintes comandos:
USE CURSO
SELECT @@SPID
BEGIN TRAN
	UPDATE TAB_1 SET CAMPO1 = 11 WHERE CAMPO1 = 1
	WAITFOR DELAY '00:00:20'
	UPDATE TAB_2 SET CAMPO1 = 55 WHERE CAMPO1 = 5
COMMIT
