--SESSÃO 2
--3. Abrir outra sessão e execute os seguintes comandos:
USE CURSO
SELECT @@SPID
BEGIN TRAN
UPDATE TAB_2 SET CAMPO1 = 111 WHERE CAMPO1 = 5
WAITFOR DELAY '00:00:20'
UPDATE TAB_1 SET CAMPO1 = 555 WHERE CAMPO1 = 1
COMMIT

