
DBCC HELP (CHECKALLOC)
--Verifica a integridade lógica e física de todos os objetos do banco de 
--dados especificado com a execução das seguintes operações:
USE MASTER
ALTER DATABASE CURSO SET SINGLE_USER  

--use curso
--GERA INFORMAÇÕES
DBCC CHECKDB (curso)
DBCC CHECKDB (curso)WITH NO_INFOMSGS, ALL_ERRORMSGS
--EM CASO DE ERROS, COLOCAR O BANCO EM EMERGENCY E SINGLE_USER

--REPARAÇÃO RAPIDA SEM PERDER DADOS
DBCC CHECKDB (curso,REPAIR_FAST) WITH NO_INFOMSGS, ALL_ERRORMSGS
--REPARAÇÃO SEM PERDER DADOS
DBCC CHECKDB (curso,REPAIR_REBUILD) WITH NO_INFOMSGS, ALL_ERRORMSGS
--ATENÇÃO
--REPARAÇÃO COM PERDER DADOS
DBCC CHECKDB (curso,REPAIR_ALLOW_DATA_LOSS) WITH NO_INFOMSGS, ALL_ERRORMSGS


--Verifica a integridade de todas as páginas e estruturas 
--que compõem a tabela ou a exibição indexada
USE CURSO
DBCC CHECKTABLE (PESSOA)
--REPARAÇÃO RAPIDA SEM PERDER DADOS
DBCC CHECKTABLE (PESSOA,REPAIR_FAST )WITH NO_INFOMSGS, ALL_ERRORMSGS
--REPARAÇÃO SEM PERDER DADOS
DBCC CHECKTABLE (PESSOA,REPAIR_REBUILD )WITH NO_INFOMSGS, ALL_ERRORMSGS
--ATENÇÃO
--REPARAÇÃO COM PERDER DADOS
DBCC CHECKTABLE (PESSOA,REPAIR_ALLOW_DATA_LOSS )WITH NO_INFOMSGS, ALL_ERRORMSGS


--Inspeciona a integridade de uma restrição especificada ou de todas as 
--restrições em uma tabela especificada no banco de dados atual.

DBCC CHECKCONSTRAINTS

--Verifica a consistência de estruturas de alocação de espaço em disco
-- para um banco de dados especificado

DBCC CHECKALLOC 
DBCC CHECKALLOC (CURSO) WITH NO_INFOMSGS, ALL_ERRORMSGS


--REPARAÇÃO RAPIDA SEM PERDER DADOS
DBCC CHECKALLOC (curso,REPAIR_FAST) WITH NO_INFOMSGS, ALL_ERRORMSGS
--REPARAÇÃO SEM PERDER DADOS
DBCC CHECKALLOC (curso,REPAIR_REBUILD) WITH NO_INFOMSGS, ALL_ERRORMSGS
--ATENÇÃO
--REPARAÇÃO COM PERDER DADOS
DBCC CHECKALLOC (curso,REPAIR_ALLOW_DATA_LOSS) WITH NO_INFOMSGS, ALL_ERRORMSGS

--VOLTAR O BANCO MULTI_USER

ALTER  DATABASE CURSO SET MULTI_USER