--Confurando BK no agent
--1 Passo BK
BEGIN 
--DECLARA VARIAVEIS
	declare @CAMINHO VARCHAR(20)
	declare @NOME_BANCO VARCHAR(20)
	declare @DATA VARCHAR(10)
	declare @EXTENSAO CHAR(4)
	declare @SQL_1 VARCHAR(MAX)
	--ATRIBUI VALORES
	SET @CAMINHO='M:\SQL001\Agent\'
	SET @NOME_BANCO='curso'
	SET @DATA = CONVERT(nvarchar(10), GETDATE(), 104)
	SET @EXTENSAO='.bak'
	--ATRIBUI OS VALOR CONCATENANDO VALORES
	SET @SQL_1=CONCAT('BACKUP DATABASE ',@NOME_BANCO,' TO DISK =N''',@CAMINHO,@NOME_BANCO,@DATA,@EXTENSAO,'''', ' WITH NOFORMAT, 
	NOINIT, 
	SKIP, NOREWIND, 
	NOUNLOAD, STATS = 10')
	--SELECT @SQL_1
	--EXECUTA COMANDO
	EXEC (@SQL_1)
END
