--drop DATABASE DB_CONN
--CRIAR O BANCO DE TABELAS INSTANCIA MSSQLSERVER002
--CRIANDO DATABASE
CREATE DATABASE DB_CONN

USE DB_CONN

--ESTE BLOCO SERA CRIANDO NO SERVIDOR QUE SERA ACESSADO
--CRIANDO DATABASE

--CRIANDO TABELA

CREATE TABLE PESSOAS   
    (      
	  ID   INT IDENTITY(1,1)  NOT NULL,      
	  NOME VARCHAR(50) NULL,      
      CONSTRAINT pktable1 PRIMARY KEY CLUSTERED (id)   
     ) 
--INSERINDO VALORES
INSERT PESSOAS (nome) VALUES 
('JOÃO'),  ('JEFF'), ('DANTE'), ('CHRIS'), ('DAVE')

--VERIFICAR O REGISTROS

SELECT * FROM PESSOAS

--CRIAR USUARIO PARA CONEXÃO
--VERIFICAR CONFIGURATION MANAGER NAMED PIPES E TCP/IP

